version: '3'

services:
    php:
        build: docker/php/
        image: matthiasnoback/aggregate-design-workshop-php
        volumes:
            - ./:/app:cached
        user: ${HOST_UID}:${HOST_GID}

    composer:
        image: composer:latest
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ./:/app:cached
