services:
    php:
        build: docker/php/
        image: matthiasnoback/aggregate-design-workshop-php
        volumes:
            - ./:/app:cached
        env_file:
            - .env
        user: "$HOST_UID:$HOST_GID"

    composer:
        image: composer:latest
        volumes:
            - ./:/app:cached
        env_file:
            - .env
        user: "$HOST_UID:$HOST_GID"
